1)
SELECT CHECK_ID, PAYEE, AMOUNT
FROM CHECKS
WHERE PAYEE LIKE 'M%' OR PAYEE LIKE 'P%';

2)
SELECT CHECK_ID, PAYEE, AMOUNT
FROM CHECKS
WHERE REMARKS LIKE '%Car%';

3)
SELECT DISTINCT PAYEE
FROM CHECKS
WHERE AMOUNT > 200.00;

4)
SELECT *
FROM CHECKS
ORDER BY AMOUNT DESC;

5)
SELECT CHECK_ID, PAYEE, AMOUNT
FROM CHECKS
WHERE REMARKS LIKE '%Shoes%' OR REMARKS LIKE '%Groceries%';

