1)
SELECT DISTINCT SNAME 
FROM STUDENT, CLASS, ENROLLED
WHERE FID = 45 
AND LEVEL = 'JUNIOR'
AND NAME = CNAME
AND STUDENT.SNUM = ENROLLED.SNUM;

2)
SELECT MAX(AGE) 
FROM STUDENT
WHERE (STUDENT.MAJOR = 'HISTORY')
OR (STUDENT.SNUM IN (SELECT ENROLLED.SNUM
			FROM CLASS, ENROLLED
			WHERE FID = 45
			AND NAME = CNAME));

3)
SELECT DISTINCT CLASS.NAME 
FROM CLASS
WHERE (CLASS.ROOM = 'R128')
OR (CLASS.NAME IN (SELECT ENROLLED.CNAME 
		   FROM ENROLLED
		   GROUP BY ENROLLED.CNAME
		   HAVING COUNT(*)>=3));

4)
SELECT DISTINCT STUDENT.SNAME
FROM STUDENT 
WHERE STUDENT.SNUM IN (SELECT E1.SNUM
		       FROM ENROLLED E1, ENROLLED E2, CLASS C1, CLASS C2
		       WHERE E1.SNUM = E2.SNUM
		       AND E1.CNAME <> E2.CNAME
		       AND E1.CNAME = C1.NAME 
		       AND E2.CNAME = C2.NAME
		       AND C1.MEETSAT = C2.MEETSAT);


5)
SELECT DISTINCT FACULTY.NAME
FROM FACULTY 
WHERE NOT EXISTS (SELECT *
		  FROM CLASS C1
		  WHERE C1.ROOM NOT IN (SELECT C2.ROOM 
					FROM CLASS C2
					WHERE FACULTY.FID = C2.FID));

6)
SELECT DISTINCT FNAME 
FROM FACULTY
WHERE 5>(SELECT COUNT(ENROLLED.SNUM)
	 FROM CLASS, ENROLLED
	 WHERE NAME=CNAME 
	 AND CLASS.FID = FACULTY.FID);

7)
SELECT LEVEL, AVG(AGE)
FROM STUDENT
GROUP BY LEVEL;

8)
SELECT LEVEL, AVG(AGE)
FROM STUDENT
WHERE LEVEL <> 'JUNIOR'
GROUP BY LEVEL;